// <auto-generated />
using System;
using CinemaProject.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CinemaProject.Migrations
{
    [DbContext(typeof(CinemaDbContext))]
    [Migration("20260312081635_initialcreate")]
    partial class initialcreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CinemaProject.Persistence.Cart", b =>
                {
                    b.Property<int>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CartId"));

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<int>("FilmScreeningId")
                        .HasColumnType("integer");

                    b.Property<int>("TicketId")
                        .HasColumnType("integer");

                    b.Property<int>("TotalPrice")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("CartId");

                    b.HasIndex("FilmScreeningId");

                    b.HasIndex("TicketId");

                    b.HasIndex("UserId");

                    b.ToTable("carts");
                });

            modelBuilder.Entity("CinemaProject.Persistence.CategoriesForHTML", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CategoryId");

                    b.ToTable("categoriesForHTML");
                });

            modelBuilder.Entity("CinemaProject.Persistence.FilmScreening", b =>
                {
                    b.Property<int>("FilmScreeningId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FilmScreeningId"));

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MovieId")
                        .HasColumnType("integer");

                    b.Property<string>("MovieTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("FilmScreeningId");

                    b.HasIndex("MovieId");

                    b.HasIndex("RoomId");

                    b.ToTable("filmScreenings");
                });

            modelBuilder.Entity("CinemaProject.Persistence.Image", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ImageId"));

                    b.Property<byte[]>("ImageContent")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("ImageId");

                    b.ToTable("images");
                });

            modelBuilder.Entity("CinemaProject.Persistence.Movie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MovieId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ImageId")
                        .HasColumnType("integer");

                    b.Property<string>("MovieTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("MovieId");

                    b.HasIndex("ImageId");

                    b.ToTable("movies");
                });

            modelBuilder.Entity("CinemaProject.Persistence.PaymentReservation", b =>
                {
                    b.Property<int>("PaymentReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PaymentReservationId"));

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<int>("CartId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FilmScreeningId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("boolean");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("PaymentReservationId");

                    b.HasIndex("CartId");

                    b.HasIndex("FilmScreeningId");

                    b.HasIndex("UserId");

                    b.ToTable("paymentReservations");
                });

            modelBuilder.Entity("CinemaProject.Persistence.Receipt", b =>
                {
                    b.Property<int>("ReceiptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReceiptId"));

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<string>("MovieTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("PaymentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PaymentReservationId")
                        .HasColumnType("integer");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ScreeningDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TicketId")
                        .HasColumnType("integer");

                    b.Property<int>("TotalPrice")
                        .HasColumnType("integer");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ReceiptId");

                    b.HasIndex("PaymentReservationId");

                    b.ToTable("receipts");
                });

            modelBuilder.Entity("CinemaProject.Persistence.ReservationConfirmation", b =>
                {
                    b.Property<int>("ConfirmationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ConfirmationId"));

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<string>("MovieTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PaymentReservationId")
                        .HasColumnType("integer");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ScreeningDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TicketId")
                        .HasColumnType("integer");

                    b.Property<int>("TotalPrice")
                        .HasColumnType("integer");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ConfirmationId");

                    b.HasIndex("PaymentReservationId");

                    b.ToTable("reservationConfirmations");
                });

            modelBuilder.Entity("CinemaProject.Persistence.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoomId"));

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RoomId");

                    b.ToTable("rooms");
                });

            modelBuilder.Entity("CinemaProject.Persistence.Seat", b =>
                {
                    b.Property<int>("SeatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SeatId"));

                    b.Property<int?>("CartId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsReserved")
                        .HasColumnType("boolean");

                    b.Property<int?>("ReceiptId")
                        .HasColumnType("integer");

                    b.Property<int?>("ReservationConfirmationConfirmationId")
                        .HasColumnType("integer");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.Property<int>("RowNumber")
                        .HasColumnType("integer");

                    b.Property<int>("SeatNumber")
                        .HasColumnType("integer");

                    b.HasKey("SeatId");

                    b.HasIndex("CartId");

                    b.HasIndex("ReceiptId");

                    b.HasIndex("ReservationConfirmationConfirmationId");

                    b.HasIndex("RoomId");

                    b.ToTable("seats");
                });

            modelBuilder.Entity("CinemaProject.Persistence.Ticket", b =>
                {
                    b.Property<int>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TicketId"));

                    b.Property<int?>("FilmScreeningId")
                        .HasColumnType("integer");

                    b.Property<int>("TicketPrice")
                        .HasColumnType("integer");

                    b.Property<string>("TicketType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TicketId");

                    b.HasIndex("FilmScreeningId");

                    b.ToTable("tickets");
                });

            modelBuilder.Entity("CinemaProject.Persistence.TicketForHTML", b =>
                {
                    b.Property<int>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TicketId"));

                    b.Property<int>("TicketPrice")
                        .HasColumnType("integer");

                    b.Property<string>("TicketType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TicketId");

                    b.ToTable("ticketsForHTML");
                });

            modelBuilder.Entity("CinemaProject.Persistence.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("BillingAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("CinemaProject.Persistence.Cart", b =>
                {
                    b.HasOne("CinemaProject.Persistence.FilmScreening", "FilmScreening")
                        .WithMany()
                        .HasForeignKey("FilmScreeningId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaProject.Persistence.Ticket", "Ticket")
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaProject.Persistence.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FilmScreening");

                    b.Navigation("Ticket");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CinemaProject.Persistence.FilmScreening", b =>
                {
                    b.HasOne("CinemaProject.Persistence.Movie", "Movie")
                        .WithMany("FilmScreenings")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaProject.Persistence.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("CinemaProject.Persistence.Movie", b =>
                {
                    b.HasOne("CinemaProject.Persistence.Image", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Image");
                });

            modelBuilder.Entity("CinemaProject.Persistence.PaymentReservation", b =>
                {
                    b.HasOne("CinemaProject.Persistence.Cart", "Cart")
                        .WithMany()
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaProject.Persistence.FilmScreening", "FilmScreening")
                        .WithMany()
                        .HasForeignKey("FilmScreeningId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaProject.Persistence.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("FilmScreening");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CinemaProject.Persistence.Receipt", b =>
                {
                    b.HasOne("CinemaProject.Persistence.PaymentReservation", "PaymentReservation")
                        .WithMany()
                        .HasForeignKey("PaymentReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PaymentReservation");
                });

            modelBuilder.Entity("CinemaProject.Persistence.ReservationConfirmation", b =>
                {
                    b.HasOne("CinemaProject.Persistence.PaymentReservation", "PaymentReservation")
                        .WithMany()
                        .HasForeignKey("PaymentReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PaymentReservation");
                });

            modelBuilder.Entity("CinemaProject.Persistence.Seat", b =>
                {
                    b.HasOne("CinemaProject.Persistence.Cart", "Cart")
                        .WithMany("Seats")
                        .HasForeignKey("CartId");

                    b.HasOne("CinemaProject.Persistence.Receipt", null)
                        .WithMany("Seats")
                        .HasForeignKey("ReceiptId");

                    b.HasOne("CinemaProject.Persistence.ReservationConfirmation", null)
                        .WithMany("Seats")
                        .HasForeignKey("ReservationConfirmationConfirmationId");

                    b.HasOne("CinemaProject.Persistence.Room", "Room")
                        .WithMany("Seats")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("CinemaProject.Persistence.Ticket", b =>
                {
                    b.HasOne("CinemaProject.Persistence.FilmScreening", "FilmScreening")
                        .WithMany()
                        .HasForeignKey("FilmScreeningId");

                    b.Navigation("FilmScreening");
                });

            modelBuilder.Entity("CinemaProject.Persistence.Cart", b =>
                {
                    b.Navigation("Seats");
                });

            modelBuilder.Entity("CinemaProject.Persistence.Movie", b =>
                {
                    b.Navigation("FilmScreenings");
                });

            modelBuilder.Entity("CinemaProject.Persistence.Receipt", b =>
                {
                    b.Navigation("Seats");
                });

            modelBuilder.Entity("CinemaProject.Persistence.ReservationConfirmation", b =>
                {
                    b.Navigation("Seats");
                });

            modelBuilder.Entity("CinemaProject.Persistence.Room", b =>
                {
                    b.Navigation("Seats");
                });
#pragma warning restore 612, 618
        }
    }
}
